export const CONFIGS = {
  directEasy: {
    id: "directEasy",
    mode: "direct",
    label: "Direct Mapping Easy",
    color: "#22c55e",
    colorLight: "#f0fdf4",
    colorBorder: "#86efac",
    colorDark: "#14532d",
    lines: 8,
    sets: null,
    waysPerSet: null,
    tagBits: 4,
    indexBits: 3,
    setBits: 0,
    offsetBits: 1,
    totalBits: 8,
    description: "Each memory address maps to exactly one cache line determined by the index bits. Use the index to find the line, then check the tag to confirm it holds the right data.",
    rules: [
      { part: "tag",    role: "Verify: does the stored tag match? If not → cache miss" },
      { part: "index",  role: "Locate: the one and only line this address can occupy" },
      { part: "offset", role: "Select: which byte within the cache line" },
    ],
  },
  directMedium: {
    id: "directMedium",
    mode: "direct",
    label: "Direct Mapping Medium",
    color: "#22c55e",
    colorLight: "#f0fdf4",
    colorBorder: "#86efac",
    colorDark: "#14532d",
    lines: 8,
    sets: null,
    waysPerSet: null,
    tagBits: 4,
    indexBits: 4,
    setBits: 0,
    offsetBits: 2,
    totalBits: 10,
    description: "Each memory address maps to exactly one cache line determined by the index bits. Use the index to find the line, then check the tag to confirm it holds the right data.",
    rules: [
      { part: "tag",    role: "Verify: does the stored tag match? If not → cache miss" },
      { part: "index",  role: "Locate: the one and only line this address can occupy" },
      { part: "offset", role: "Select: which byte within the cache line" },
    ],
  },
  directHard: {
    id: "directHard",
    mode: "direct",
    label: "Direct Mapping Hard",
    color: "#22c55e",
    colorLight: "#f0fdf4",
    colorBorder: "#86efac",
    colorDark: "#14532d",
    lines: 8,
    sets: null,
    waysPerSet: null,
    tagBits: 4,
    indexBits: 5,
    setBits: 0,
    offsetBits: 2,
    totalBits: 11,
    hideAddressLabels: true,
    description: "Each memory address maps to exactly one cache line determined by the index bits. Use the index to find the line, then check the tag to confirm it holds the right data.",
    rules: [
      { part: "tag",    role: "Verify: does the stored tag match? If not → cache miss" },
      { part: "index",  role: "Locate: the one and only line this address can occupy" },
      { part: "offset", role: "Select: which byte within the cache line" },
    ],
  },
  setEasy: {
    id: "setEasy",
    mode: "set",
    label: "Set-Associative Easy",
    color: "#f59e0b",
    colorLight: "#fffbeb",
    colorBorder: "#fbbf24",
    colorDark: "#78350f",
    lines: 8,
    sets: 4,
    waysPerSet: 2,
    tagBits: 5,
    indexBits: 0,
    setBits: 2,
    offsetBits: 1,
    totalBits: 8,
    description: "The cache is split into sets, each holding multiple lines. Set bits identify which set this address belongs to. The data can be placed in any line within that set. Tag bits identify which specific line holds the data.",
    rules: [
      { part: "tag",    role: "Identify: which line in the set holds this data — miss if no tags match" },
      { part: "set",    role: "Locate: which set of lines this address belongs to" },
      { part: "offset", role: "Select: which byte within the cache line" },
    ],
  },
  setMedium: {
    id: "setMedium",
    mode: "set",
    label: "Set-Associative Medium",
    color: "#f59e0b",
    colorLight: "#fffbeb",
    colorBorder: "#fbbf24",
    colorDark: "#78350f",
    lines: 12,
    sets: 4,
    waysPerSet: 3,
    tagBits: 5,
    indexBits: 0,
    setBits: 2,
    offsetBits: 1,
    totalBits: 8,
    description: "The cache is split into sets, each holding multiple lines. Set bits identify which set this address belongs to. The data can be placed in any line within that set. Tag bits identify which specific line holds the data.",
    rules: [
      { part: "tag",    role: "Identify: which line in the set holds this data — miss if no tags match" },
      { part: "set",    role: "Locate: which set of lines this address belongs to" },
      { part: "offset", role: "Select: which byte within the cache line" },
    ],
  },
  setHard: {
    id: "setHard",
    mode: "set",
    label: "Set-Associative Hard",
    color: "#f59e0b",
    colorLight: "#fffbeb",
    colorBorder: "#fbbf24",
    colorDark: "#78350f",
    lines: 8,
    sets: 4,
    waysPerSet: 2,
    tagBits: 5,
    setBits: 2,
    offsetBits: 1,
    totalBits: 8,
    hideAddressLabels: true,
    description: "The cache is split into sets, each holding multiple lines. Set bits identify which set this address belongs to. The data can be placed in any line within that set. Tag bits identify which specific line holds the data.",
    rules: [
      { part: "tag",    role: "Identify: which line in the set holds this data — miss if no tags match" },
      { part: "set",    role: "Locate: which set of lines this address belongs to" },
      { part: "offset", role: "Select: which byte within the cache line" },
    ],
  },
  associativeEasy: {
    id: "associativeEasy",
    mode: "associative",
    label: "Fully Associative Easy",
    color: "#8b5cf6",
    colorLight: "#f5f3ff",
    colorBorder: "#c4b5fd",
    colorDark: "#4c1d95",
    lines: 8,
    tagBits: 7,
    indexBits: 0,
    setBits: 0,
    offsetBits: 1,
    totalBits: 8,
    description: "Memory can be placed in any cache line — there are no index or set bits. Every tag in every line must be compared on each lookup. A miss only occurs when no stored tag matches.",
    rules: [
      { part: "tag",    role: "Compare ALL lines — if no stored tag matches → cache miss" },
      { part: "offset", role: "Select: which byte within the cache line" },
    ],
  },
   associativeMedium: {
    id: "associativeMedium",
    mode: "associative",
    label: "Fully Associative Medium",
    color: "#8b5cf6",
    colorLight: "#f5f3ff",
    colorBorder: "#c4b5fd",
    colorDark: "#4c1d95",
    lines: 16,
    tagBits: 7,
    indexBits: 0,
    setBits: 0,
    offsetBits: 1,
    totalBits: 8,
    description: "Memory can be placed in any cache line — there are no index or set bits. Every tag in every line must be compared on each lookup. A miss only occurs when no stored tag matches.",
    rules: [
      { part: "tag",    role: "Compare ALL lines — if no stored tag matches → cache miss" },
      { part: "offset", role: "Select: which byte within the cache line" },
    ],
  },
   associativeHard: {
    id: "associativeHard",
    mode: "associative",
    label: "Fully Associative Hard",
    color: "#8b5cf6",
    colorLight: "#f5f3ff",
    colorBorder: "#c4b5fd",
    colorDark: "#4c1d95",
    lines: 8,
    tagBits: 7,
    indexBits: 0,
    setBits: 0,
    offsetBits: 1,
    totalBits: 8,
    hideAddressLabels: true,
    description: "Memory can be placed in any cache line — there are no index or set bits. Every tag in every line must be compared on each lookup. A miss only occurs when no stored tag matches.",
    rules: [
      { part: "tag",    role: "Compare ALL lines — if no stored tag matches → cache miss" },
      { part: "offset", role: "Select: which byte within the cache line" },
    ],
  },
};