export const MODE_DESCRIPTIONS = {
  associative: {
    id: "associative",
    label: "Fully Associative",
    tag: "Mode 1 · Beginner",
    color: "#8b5cf6", colorLight: "#f5f3ff", colorBorder: "#c4b5fd", colorDark: "#4c1d95",
    maxXp: 100,
    desc: "Memory can go in any cache line — no index or set bits. Every tag must be compared. Miss only when no tags match.",
    bits: [
      { part: "tag", role: "Compare ALL lines — miss if no stored tag matches" },
      { part: "offset", role: "Which byte within the cache line" },
    ],
  },
  direct: {
    id: "direct",
    label: "Direct Mapping",
    tag: "Mode 2 · Intermediate",
    color: "#22c55e", colorLight: "#f0fdf4", colorBorder: "#86efac", colorDark: "#14532d",
    maxXp: 200,
    desc: "Each memory address maps to exactly one cache line. Index bits locate the line; tag bits verify the data is correct.",
    bits: [
      { part: "tag", role: "Verify correct data is loaded — miss if tags don't match" },
      { part: "index", role: "Points to the exact cache line (one line only)" },
      { part: "offset", role: "Which byte within that cache line" },
    ]
  },
  set: {
    id: "set",
    label: "Set-Associative",
    tag: "Mode 3 · Advanced",
    color: "#f59e0b", colorLight: "#fffbeb", colorBorder: "#fbbf24", colorDark: "#78350f",
    maxXp: 300,
    desc: "Cache is split into sets. Set bits identify which set this address belongs to. Data can go in any line within that set.",
    bits: [
      { part: "tag", role: "Identify which row within the set — miss if no tags match" },
      { part: "set", role: "Which set of lines this address belongs to" },
      { part: "offset", role: "Which byte within the cache line" },
    ]
  } 
}

export const CONFIGS = {
  associativeEasy: {
    id: "associativeEasy",
    mode: "associative",
    label: "Fully Associative Easy",
    color: "#8b5cf6",
    colorLight: "#f5f3ff",
    colorBorder: "#c4b5fd",
    colorDark: "#4c1d95",
    lines: 8,
    tagBits: 7,
    indexBits: 0,
    setBits: 0,
    offsetBits: 1,
    totalBits: 8,
    description: MODE_DESCRIPTIONS.associative.desc,
    rules: MODE_DESCRIPTIONS.associative.bits,
  },
  associativeMedium: {
    id: "associativeMedium",
    mode: "associative",
    label: "Fully Associative Medium",
    color: "#8b5cf6",
    colorLight: "#f5f3ff",
    colorBorder: "#c4b5fd",
    colorDark: "#4c1d95",
    lines: 16,
    tagBits: 7,
    indexBits: 0,
    setBits: 0,
    offsetBits: 2,
    totalBits: 9,
    description: MODE_DESCRIPTIONS.associative.desc,
    rules: MODE_DESCRIPTIONS.associative.bits,
  },
  associativeHard: {
    id: "associativeHard",
    mode: "associative",
    label: "Fully Associative Hard",
    color: "#8b5cf6",
    colorLight: "#f5f3ff",
    colorBorder: "#c4b5fd",
    colorDark: "#4c1d95",
    lines: 8,
    tagBits: 7,
    indexBits: 0,
    setBits: 0,
    offsetBits: 2,
    totalBits: 9,
    hideAddressLabels: true,
    description: MODE_DESCRIPTIONS.associative.desc,
    rules: MODE_DESCRIPTIONS.associative.bits,
  },
  directEasy: {
    id: "directEasy",
    mode: "direct",
    label: "Direct Mapping Easy",
    color: "#47a201",
    colorLight: "#f0fbe5",
    colorBorder: "#06a342",
    colorDark: "#14532d",
    lines: 8,
    sets: null,
    waysPerSet: null,
    tagBits: 4,
    indexBits: 3,
    setBits: 0,
    offsetBits: 1,
    totalBits: 8,
    description: MODE_DESCRIPTIONS.direct.desc,
    rules: MODE_DESCRIPTIONS.direct.bits,
  },
  directMedium: {
    id: "directMedium",
    mode: "direct",
    label: "Direct Mapping Medium",
    color: "#47a201",
    colorLight: "#f0fbe5",
    colorBorder: "#06a342",
    colorDark: "#14532d",
    lines: 8,
    sets: null,
    waysPerSet: null,
    tagBits: 4,
    indexBits: 4,
    setBits: 0,
    offsetBits: 2,
    totalBits: 10,
    description: MODE_DESCRIPTIONS.direct.desc,
    rules: MODE_DESCRIPTIONS.direct.bits,
  },
  directHard: {
    id: "directHard",
    mode: "direct",
    label: "Direct Mapping Hard",
    color: "#47a201",
    colorLight: "#f0fbe5",
    colorBorder: "#06a342",
    colorDark: "#14532d",
    lines: 8,
    sets: null,
    waysPerSet: null,
    tagBits: 4,
    indexBits: 5,
    setBits: 0,
    offsetBits: 2,
    totalBits: 11,
    hideAddressLabels: true,
    description: MODE_DESCRIPTIONS.direct.desc,
    rules: MODE_DESCRIPTIONS.direct.bits,
  },
  setEasy: {
    id: "setEasy",
    mode: "set",
    label: "Set-Associative Easy",
    color: "#f59e0b",
    colorLight: "#fffbeb",
    colorBorder: "#fbbf24",
    colorDark: "#78350f",
    lines: 8,
    sets: 4,
    waysPerSet: 2,
    tagBits: 5,
    indexBits: 0,
    setBits: 2,
    offsetBits: 1,
    totalBits: 8,
    description: MODE_DESCRIPTIONS.set.desc,
    rules: MODE_DESCRIPTIONS.set.bits,
  },
  setMedium: {
    id: "setMedium",
    mode: "set",
    label: "Set-Associative Medium",
    color: "#f59e0b",
    colorLight: "#fffbeb",
    colorBorder: "#fbbf24",
    colorDark: "#78350f",
    lines: 12,
    sets: 4,
    waysPerSet: 3,
    tagBits: 5,
    indexBits: 0,
    setBits: 2,
    offsetBits: 1,
    totalBits: 8,
    description: MODE_DESCRIPTIONS.set.desc,
    rules: MODE_DESCRIPTIONS.set.bits,
  },
  setHard: {
    id: "setHard",
    mode: "set",
    label: "Set-Associative Hard",
    color: "#f59e0b",
    colorLight: "#fffbeb",
    colorBorder: "#fbbf24",
    colorDark: "#78350f",
    lines: 12,
    sets: 4,
    waysPerSet: 3,
    tagBits: 5,
    setBits: 2,
    offsetBits: 1,
    totalBits: 8,
    hideAddressLabels: true,
    description: MODE_DESCRIPTIONS.set.desc,
    rules: MODE_DESCRIPTIONS.set.bits,
  },
};



// Each step is an array of parts:
//   string                                        → plain text
//   { badge: "tag"|"index"|"set"|"offset", text } → coloured badge
//   { strong: string }                            → bold text
//   { sub: part[][] }                             → nested sub-list
export const MODE_INSTRUCTIONS = {
  direct: [
    [
      "Extract the ", { badge: "offset", text: "offset" }, " bits.",
      { sub: [
        ["The block size tells you how many offset bits are needed."],
      ]},
    ],
    [
      "Extract the ", { badge: "index", text: "index" }, " bits.",
      { sub: [
        ["Determined by the number of lines in the cache."],
        ["Take index value modulo the number of cache lines to get the target line."],
      ]},
    ],
    [
      "The remaining bits are all ", { badge: "tag", text: "tag" }, " bits.",
    ],
    ["Compare the address ", { badge: "tag", text: "tag" }, " to the stored tag on that line."],
    ["Tags match → ", { strong: "cache hit" }, ". Click the correct byte in that row."],
    ["Tags differ → click ", { strong: "Cache miss" }, "."],
  ],
  set: [
    [
      "Extract the ", { badge: "offset", text: "offset" }, " bits.",
      { sub: [
        ["The block size tells you how many offset bits are needed."],
      ]},
    ],
    [
      "Extract the ", { badge: "set", text: "set" }, " bits.",
      { sub: [
        ["The number of sets tells you how many set bits are needed."],
      ]},
    ],
    [
      "The remaining bits are all ", { badge: "tag", text: "tag" }, " bits.",
    ],
    ["Check every line in that set for a matching ", { badge: "tag", text: "tag" }, "."],
    ["A tag matches → ", { strong: "cache hit" }, ". Click that line."],
    ["No tag matches → click ", { strong: "Cache miss" }, "."],
  ],
  associative: [
    [
      "Extract the ", { badge: "offset", text: "offset" }, " bits.",
      { sub: [
        ["The block size tells you how many offset bits are needed."],
      ]},
    ],
    [
      "The remaining bits are all ", { badge: "tag", text: "tag" }, " bits.",
    ],
    ["Scan ", { strong: "every" }, " cache line for a matching ", { badge: "tag", text: "tag" }, "."],
    ["A tag matches → ", { strong: "cache hit" }, ". Click that line."],
    ["No tag matches anywhere → click ", { strong: "Cache miss" }, "."],
  ],
};